[project]
name = "thesis-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.1",
    "neptune>=1.13.0",
    "pandas>=2.2.3",
    "seaborn>=0.13.2",
]
